name: "[CI] Continuous Integration"

on:
   pull_request:
    types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: "Debug"
              run: "ls -la"
            - name: "Install Dependecies"
              run: "npm install"
            - name: "Lint"
              run: "npm run lint"
    test:
        runs-on: ubuntu-latest
        container: cypress/browsers:node20.11.0-chrome122
        steps:
            - uses: actions/checkout@v3
            - name: "Install Dependencies"
              run: "npm install"
            - name: "Cypress"
              run: "npm run test"
